### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by desmovalvo** [arces-wot/SEPA#21] opened 2017-10-10 10:12 UTC
Closing and re-starting SEPA I **often** get this exception:

`java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processSessionRequests(DefaultListeningIOReactor.java:243)
	at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processEvents(DefaultListeningIOReactor.java:144)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.bootstrap.HttpServer$2.run(HttpServer.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.apache.http.nio.reactor.IOReactorException: Failure binding socket to address 0.0.0.0/0.0.0.0:8000
	at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processSessionRequests(DefaultListeningIOReactor.java:248)
	at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processEvents(DefaultListeningIOReactor.java:144)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.bootstrap.HttpServer$2.run(HttpServer.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processSessionRequests(DefaultListeningIOReactor.java:243)
	... 6 more`

Then I have to wait some minutes before being able to re-start the SEPA again.

**Comment by lroffia** [comment] 2017-10-10 10:13
I know. I should have fixed it in the current version I will push soon

**Comment by lroffia** [comment] 2017-10-10 10:19
Pushed new version. Please try and let me known. Here the console output:

##########################################################################################
# SEPA Engine Ver 0.8.2  Copyright (C) 2016-2017                                         #
# Web of Things Research @ ARCES - University of Bologna (Italy)                         #
#                                                                                        #
# This program comes with ABSOLUTELY NO WARRANTY                                         #
# This is free software, and you are welcome to redistribute it under certain conditions #
# GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007                                    #
#                                                                                        #
# GITHUB: https://github.com/arces-wot/sepa                                              #
# WEB: http://wot.arces.unibo.it                                                         #
# WIKI: https: // github.com/arces-wot/SEPA/wiki                                         #
##########################################################################################
2017-10-10 12:18:49,963 main (AuthorizationManager.java:116) [DEBUG] *** Security check ***
2017-10-10 12:18:49,965 main (AuthorizationManager.java:121) [DEBUG] Register: b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:306) [DEBUG] Register: b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:259) [DEBUG] Authorize identity:b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:126) [DEBUG] ID:SECRET=9192a9fd-c65b-4fed-b586-3dbd5b2efa5e:353c8335-df70-42c8-a64f-ed9ab46b2fcd
2017-10-10 12:18:49,966 main (AuthorizationManager.java:130) [DEBUG] Authorization Basic OTE5MmE5ZmQtYzY1Yi00ZmVkLWI1ODYtM2RiZDViMmVmYTVlOjM1M2M4MzM1LWRmNzAtNDJjOC1hNjRmLWVkOWFiNDZiMmZjZA==
2017-10-10 12:18:49,967 main (AuthorizationManager.java:359) [DEBUG] Get token
2017-10-10 12:18:49,967 main (AuthorizationManager.java:383) [DEBUG] Credentials: 9192a9fd-c65b-4fed-b586-3dbd5b2efa5e 353c8335-df70-42c8-a64f-ed9ab46b2fcd
2017-10-10 12:18:50,012 main (AuthorizationManager.java:134) [DEBUG] Access token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJTRVBBVGVzdCIsImF1ZCI6WyJodHRwczpcL1wvd290LmFyY2VzLnVuaWJvLml0Ojg0NDNcL3NwYXJxbCIsIndzczpcL1wvd290LmFyY2VzLnVuaWJvLml0Ojk0NDNcL3NwYXJxbCJdLCJuYmYiOjE1MDc2MzA3MjgsImlzcyI6Imh0dHBzOlwvXC93b3QuYXJjZXMudW5pYm8uaXQ6ODQ0M1wvb2F1dGhcL3Rva2VuIiwiZXhwIjoxNTA3NjMwNzM0LCJpYXQiOjE1MDc2MzA3MjksImp0aSI6IjkxOTJhOWZkLWM2NWItNGZlZC1iNTg2LTNkYmQ1YjJlZmE1ZTozNTNjODMzNS1kZjcwLTQyYzgtYTY0Zi1lZDlhYjQ2YjJmY2QifQ.6qcQ9GjReCVRI6DBrOOMTW1h2nfVSEFVKd3E5iFBTXHUucRiUbuJ-Z2WJWajiOnnyvM9fr3xe2ff6To_UmmWhh1i30dFM-6LZRTEogEGHG2xZxx9kSAhCMAgHEh9YtqExp33gI76X9HjP7Hf-PcWl12aVo26YOg4Uog_0yowxoI_FW2awqeL8I2TPBDtIIQGTEJEgpZfdsYmr5EHJ6Ml_drakCvdBQtMvH5OxsovlDn_XRBr44U3uy0qScFbcc7UpzNVS-SuusTzQRPiY-PG54e9-3CpwYJk5AOzL5kN7Ut9AJz9GO4bmJu5XW4UDUBJAUom3DA8MzSFYjJ8jYH50w
2017-10-10 12:18:50,012 main (AuthorizationManager.java:525) [DEBUG] Validate token
2017-10-10 12:18:50,021 main (AuthorizationManager.java:138) [DEBUG] PASSED
2017-10-10 12:18:50,021 main (AuthorizationManager.java:147) [DEBUG] **********************

SPARQL 1.1 Protocol (https://www.w3.org/TR/sparql11-protocol/)
----------------------
SPARQL 1.1 Query     | http://192.168.1.14:8000/query
SPARQL 1.1 Update    | http://192.168.1.14:8000/update
----------------------

SPARQL 1.1 SE Protocol (https://wot.arces.unibo.it/TR/sparql11-se-protocol/)
----------------------
SPARQL 1.1 SE Query  | https://192.168.1.14:8443/secure/query
SPARQL 1.1 SE Update | https://192.168.1.14:8443/secure/update
Client registration  | https://192.168.1.14:8443/oauth/register
Token request        | https://192.168.1.14:8443/oauth/token
Subscribe            | ws://192.168.1.14:9000/subscribe
Secure Subscribe     | wss://192.168.1.14:9443/secure/subscribe
----------------------

*****************************************************************************************
*                      SEPA Engine Ver 0.8.2 is up and running                          *
*                                Let Things Talk!                                       *
*****************************************************************************************
^CStopping...
**

> Stopping HTTP gate...
> Stopping HTTPS gate...
> Stopping WS gate...
> Stopping WSS gate...
> Stopped...bye bye :-)

**

**Comment by lroffia** [comment] 2017-10-10 10:21
Here the console output:

```
##########################################################################################
# SEPA Engine Ver 0.8.2  Copyright (C) 2016-2017                                         #
# Web of Things Research @ ARCES - University of Bologna (Italy)                         #
#                                                                                        #
# This program comes with ABSOLUTELY NO WARRANTY                                         #
# This is free software, and you are welcome to redistribute it under certain conditions #
# GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007                                    #
#                                                                                        #
# GITHUB: https://github.com/arces-wot/sepa                                              #
# WEB: http://wot.arces.unibo.it                                                         #
# WIKI: https: // github.com/arces-wot/SEPA/wiki                                         #
##########################################################################################
2017-10-10 12:18:49,963 main (AuthorizationManager.java:116) [DEBUG] *** Security check ***
2017-10-10 12:18:49,965 main (AuthorizationManager.java:121) [DEBUG] Register: b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:306) [DEBUG] Register: b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:259) [DEBUG] Authorize identity:b2dcc85f-4090-4be9-816b-dadd26163069
2017-10-10 12:18:49,966 main (AuthorizationManager.java:126) [DEBUG] ID:SECRET=9192a9fd-c65b-4fed-b586-3dbd5b2efa5e:353c8335-df70-42c8-a64f-ed9ab46b2fcd
2017-10-10 12:18:49,966 main (AuthorizationManager.java:130) [DEBUG] Authorization Basic OTE5MmE5ZmQtYzY1Yi00ZmVkLWI1ODYtM2RiZDViMmVmYTVlOjM1M2M4MzM1LWRmNzAtNDJjOC1hNjRmLWVkOWFiNDZiMmZjZA==
2017-10-10 12:18:49,967 main (AuthorizationManager.java:359) [DEBUG] Get token
2017-10-10 12:18:49,967 main (AuthorizationManager.java:383) [DEBUG] Credentials: 9192a9fd-c65b-4fed-b586-3dbd5b2efa5e 353c8335-df70-42c8-a64f-ed9ab46b2fcd
2017-10-10 12:18:50,012 main (AuthorizationManager.java:134) [DEBUG] Access token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJTRVBBVGVzdCIsImF1ZCI6WyJodHRwczpcL1wvd290LmFyY2VzLnVuaWJvLml0Ojg0NDNcL3NwYXJxbCIsIndzczpcL1wvd290LmFyY2VzLnVuaWJvLml0Ojk0NDNcL3NwYXJxbCJdLCJuYmYiOjE1MDc2MzA3MjgsImlzcyI6Imh0dHBzOlwvXC93b3QuYXJjZXMudW5pYm8uaXQ6ODQ0M1wvb2F1dGhcL3Rva2VuIiwiZXhwIjoxNTA3NjMwNzM0LCJpYXQiOjE1MDc2MzA3MjksImp0aSI6IjkxOTJhOWZkLWM2NWItNGZlZC1iNTg2LTNkYmQ1YjJlZmE1ZTozNTNjODMzNS1kZjcwLTQyYzgtYTY0Zi1lZDlhYjQ2YjJmY2QifQ.6qcQ9GjReCVRI6DBrOOMTW1h2nfVSEFVKd3E5iFBTXHUucRiUbuJ-Z2WJWajiOnnyvM9fr3xe2ff6To_UmmWhh1i30dFM-6LZRTEogEGHG2xZxx9kSAhCMAgHEh9YtqExp33gI76X9HjP7Hf-PcWl12aVo26YOg4Uog_0yowxoI_FW2awqeL8I2TPBDtIIQGTEJEgpZfdsYmr5EHJ6Ml_drakCvdBQtMvH5OxsovlDn_XRBr44U3uy0qScFbcc7UpzNVS-SuusTzQRPiY-PG54e9-3CpwYJk5AOzL5kN7Ut9AJz9GO4bmJu5XW4UDUBJAUom3DA8MzSFYjJ8jYH50w
2017-10-10 12:18:50,012 main (AuthorizationManager.java:525) [DEBUG] Validate token
2017-10-10 12:18:50,021 main (AuthorizationManager.java:138) [DEBUG] PASSED
2017-10-10 12:18:50,021 main (AuthorizationManager.java:147) [DEBUG] **********************

SPARQL 1.1 Protocol (https://www.w3.org/TR/sparql11-protocol/)
----------------------
SPARQL 1.1 Query     | http://192.168.1.14:8000/query
SPARQL 1.1 Update    | http://192.168.1.14:8000/update
----------------------

SPARQL 1.1 SE Protocol (https://wot.arces.unibo.it/TR/sparql11-se-protocol/)
----------------------
SPARQL 1.1 SE Query  | https://192.168.1.14:8443/secure/query
SPARQL 1.1 SE Update | https://192.168.1.14:8443/secure/update
Client registration  | https://192.168.1.14:8443/oauth/register
Token request        | https://192.168.1.14:8443/oauth/token
Subscribe            | ws://192.168.1.14:9000/subscribe
Secure Subscribe     | wss://192.168.1.14:9443/secure/subscribe
----------------------

*****************************************************************************************
*                      SEPA Engine Ver 0.8.2 is up and running                          *
*                                Let Things Talk!                                       *
*****************************************************************************************
^CStopping...
Stopping HTTP gate...
Stopping HTTPS gate...
Stopping WS gate...
Stopping WSS gate...
Stopped...bye bye :-)
```

**Comment by relu91** [comment] 2017-11-17 15:03
It seems that the issue is fixed. I'm closing it, feel free to open it again in you find again this problem.

**Closed by relu91** 2017-11-17 15:03 UTC
Labels: bug
